### ISSUE TITLE
Add subpalettes

### ISSUE THREAD

**Issue by Munsio** [madeyourday/contao-rocksolid-custom-elements#26] opened 2014-11-28 12:41 UTC
It would be great to use subpalettes to show/hide particular fields

**Comment by MrTool** [comment] 2015-01-01 21:47
Maybe this way:
```php

'fields' => array(
       'wannaUse' => array(
            'label' => array('Wanna use?', 'Activate for textarea'),
            'inputType' => 'checkbox',
        ),
        'text' => array(
            'label' => array('Text', 'Beschreibung...'),
            'eval' => array('rte' => 'tinyMCE'),
            'inputType' => 'textarea',
            'dependsOn' => 'wannaUse'
        ),
    ),

```

At first there should be only the checkbox be available with that function.
In the second stage there could also be an key like 'dependsCallback' or something like that for subpalettes depends on a special value in an select or something like that

**Comment by Nico0o** [comment] 2015-05-31 10:37
+1

**Comment by cgpro** [comment] 2015-06-15 13:17
+1

**Comment by bondt** [comment] 2015-06-15 13:21
+1

**Comment by molokodesign** [comment] 2015-06-15 13:21
+1

**Comment by cboelter** [comment] 2015-06-15 13:55
+1

**Comment by tim-bec** [comment] 2015-07-16 10:26
+1

**Comment by jenda77** [comment] 2015-08-06 11:36
+1

**Comment by xantippe** [comment] 2015-08-13 19:13
+1

**Comment by pandroid** [comment] 2015-09-19 16:39
+1

**Comment by entepe85** [comment] 2015-09-22 13:01
+1

**Comment by mafudelaptu** [comment] 2016-01-07 08:42
+1

**Comment by NicolasGoerlach** [comment] 2016-02-25 22:53
Any news?

**Comment by jenda77** [comment] 2016-02-26 11:38
This feature would be really great. I´m looking forward to getting it. :-)

**Comment by aliasltb** [comment] 2016-03-11 11:44
I'd definitely appreciate this feature.

**Comment by Metis77** [comment] 2016-05-27 06:30
+1

**Comment by jankout** [comment] 2016-11-23 19:20
Any news?

**Comment by k-webdesign** [comment] 2017-03-06 14:49
+1

**Comment by zonky2** [comment] 2017-03-06 14:53
> Do you have a suggestion how this should look like in the element configuration?

may be it´s meta-palettes goot point to start
https://github.com/contao-community-alliance/meta-palettes

**Comment by pagestyles** [comment] 2017-03-06 19:30
+1

**Comment by ausi** [comment] 2017-05-08 12:37
I think the `dependsOn` version of @Munsio would make sense. For a more advanced check I would like to use regular expressions because they can be evaluated in PHP and JavaScript, e.g.:

```php
'dependsOn' => 'wannaUse', // Simple checkbox case
'dependsOn' => [
	'field' => 'wannaUse',
	'value' => 'foo', // Simple value case
],
'dependsOn' => [
	'field' => 'wannaUse',
	'value' => 'foo|bar|baz', // Simple regex case
],
'dependsOn' => [
	'field' => 'wannaUse',
	'value' => '.*\.html|http://.*', // Advanced regex case
],
```

Maybe `dependsOn` could also be an array of multiple conditions that all have to be met:

```php
'dependsOn' => ['wannaUse1', 'wannaUse2'],
'dependsOn' => [
	[
		'field' => 'wannaUse1',
		'value' => 'foo',
	],
	[
		'field' => 'wannaUse2',
		'value' => 'bar',
	],
],
```

**Comment by zonky2** [comment] 2017-05-09 07:59
may be as

AND
```
'dependsOn' => ['wannaUse1', 'wannaUse2'],
'dependsOn' => [
	[
		'field' => 'wannaUse1',
		'value' => 'foo',
	]
	&&
	[
		'field' => 'wannaUse2',
		'value' => 'bar',
	],
],
```

OR
```'dependsOn' => ['wannaUse1', 'wannaUse2'],
'dependsOn' => [
	[
		'field' => 'wannaUse1',
		'value' => 'foo',
	]
	||
	[
		'field' => 'wannaUse2',
		'value' => 'bar',
	],
],
```

**Comment by ausi** [comment] 2017-05-09 08:31
@zonky2 your example is not valid PHP syntax.

**Comment by zonky2** [comment] 2017-05-09 08:38
..thats true! should ony a example to add AND/OR

**Comment by btosh82** [comment] 2017-06-12 06:35
+1

**Comment by websolutions-hamburg** [comment] 2017-07-14 05:24
+1

**Comment by berecont** [comment] 2017-11-16 18:59
+1

**Comment by dhe** [comment] 2017-12-01 10:01
+1
Any new information?

**Comment by ausi** [comment] 2017-12-01 14:18
Quote from [ben.balter.com/2014/11/06/rules-of-communicating-at-github/](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/#5-be-mindful-of-noise):

> **Only comment if you have something to add to the discussion** - It’s one thing to indicate that you’ve taken the time to review a proposed change and give it a thumbs up, but adding a vanilla 👍 to a thread that already has 10 👍s, doesn’t really do much to advance the project. Unless what you’re posting moves the issue closer to resolution or the pull request closer to merge, don’t hit the green button. Just don’t do it.

**Comment by ausi** [comment] 2020-11-03 13:12
This feature is now implemented in a feature branch. Please install the version `"madeyourday/contao-rocksolid-custom-elements":"dev-feature/depends-on"` to test if this works for your use cases.

The following configurations are currently possible:

```php
'dependsOn' => 'wannaUse', // Simple checkbox case
'dependsOn' => [
	'field' => 'wannaUse',
	'value' => 'foo', // Simple value case
],
'dependsOn' => [
	'field' => 'wannaUse',
	'value' => ['foo', 'bar', 'baz'], // Multi value case
],
```

**Comment by zonky2** [comment] 2020-11-03 13:55
Does the code automatically set a submitOnChange to the field "wannaUse"?

**Comment by ausi** [comment] 2020-11-03 14:03
> Does the code automatically set a submitOnChange to the field "wannaUse"?

No, this feature works via client side JS. A reload of the page is not necessary.

**Comment by zonky2** [comment] 2020-11-03 14:03
fine!

**Comment by CONTEGRA** [comment] 2020-11-03 18:11
Feature doesn't seem to work on multiple checkbox (only first value) and radio buttons.

Here's a simple test file: [rsce_deppensOn_config.php.zip](https://github.com/madeyourday/contao-rocksolid-custom-elements/files/5483163/rsce_deppensOn_config.php.zip)

**Comment by berecont** [comment] 2020-11-03 20:14
thx for the feature!
'inputType' => 'select' ... works fine
'inputType' => 'radio' ... don't work in my simple case
'inputType' => 'checkbox' ... don't work in my simple case ... works only as 'multple' => true and in this case only on first value

**Comment by ausi** [comment] 2020-11-05 08:22
Radio buttons and checkboxes (single and multiple) should work now.

**Comment by netzarbeiter** [comment] 2020-11-05 09:33
I'm not sure if the problem is sitting in front of the screen or if it still doesn't work.

- `select` is working fine with the example below
- `radio` is working fine with the example below
- `checkbox` only shows the first option when checking the input field still has a `display:none`


```php
'question' => array(
    'options' => array(
        'question1' => 'Frage 1',
        'question2' => 'Frage 2',
    ),
    'inputType' => 'select',
    'eval' => array('tl_class' => 'w50'),
),
'answer1' => array(
    'inputType' => 'text',
    'eval' => array('tl_class' => 'w50'),
    'dependsOn' => [
        'field' => 'question',
        'value' => ['question1'],
    ],
),
'answer2' => array(
    'inputType' => 'text',
    'eval' => array('tl_class' => 'w50'),
    'dependsOn' => [
        'field' => 'question',
        'value' => ['question2'],
    ],
),
```

**Comment by ausi** [comment] 2020-11-05 09:58
To make your example work with checkboxes you need to add `'eval' => ['multiple' => true],` to the checkbox config.

For a single checkbox you don’t need to check for a `'value'` for example:

```php
'question' => array(
    'inputType' => 'checkbox',
),
'answer' => array(
    'inputType' => 'text',
    'dependsOn' => [
        'field' => 'question',
    ],
),
```

You could also use `'dependsOn' => 'question',` in this example for a shorter version.

**Comment by netzarbeiter** [comment] 2020-11-05 10:07
Thank you very much, now it works.

Is there a possibility to remove the "Select all" option from the checkbox menu?
Because clicking checkes the option, but the fields are not displayed.

**Comment by ausi** [comment] 2020-11-05 10:15
> Is there a possibility to remove the "Select all" option from the checkbox menu?

No, that is not possible in Contao I think.

> Because clicking checkes the option, but the fields are not displayed.

This should be fixed now.

**Comment by CONTEGRA** [comment] 2020-11-05 11:20
Finally it work's for my example too.

Thanks a lot!

**Comment by berecont** [comment] 2020-11-22 20:29
'inputType' => 'checkbox',
Bei Mehrfach-Option muss 'multiple' => true gesetzt werden damit auch korrekt alle Optionen angezeigt werden.
Wenn ich aber  nun nur eine der möglichen Auswahlen erlauben möchte, müsste 'multiple' => false sein. Das bringt aber wieder eine falsche Anzeige.
Aktueller workaround: 'radio' statt 'checkbox'

**Comment by Metis77** [comment] 2021-01-28 13:12
Working with this new branch and works great for us.
Are there any plans for releasing this?

**Comment by berecont** [comment] 2021-02-26 17:08
'inputType' => 'group' and 'dependsOn' do not work
`'numbersFour' => [
        'label' => ['4.Block',''],
        'inputType' => 'group',
        'dependsOn' => [
            'field' => 'numbersItems',
            'value' => 'four',
        ],
],`

**Comment by ausi** [comment] 2021-03-09 09:36
@berecont `dependsOn` should now work on `group`s too.

**Closed as completed** 2021-03-09 10:12 UTC
Labels: enhancement

**Comment by ausi** [comment] 2021-03-09 13:09
Released in version [2.3.0](https://github.com/madeyourday/contao-rocksolid-custom-elements/releases/tag/v2.3.0)

**Comment by Metis77** [comment] 2023-08-14 13:05
is `dependsOn` not working if it is nested inside a `list` but the related setting is outside the list?
Like setting once for all List items?

**Comment by ausi** [comment] 2023-08-14 13:09
@Metis77 see https://github.com/madeyourday/contao-rocksolid-custom-elements/issues/163#issuecomment-1660031364
